name:  'Tests unitários Login PGATS schedule'

on:
    schedule:
    - cron: '0 7 * * 1-5'
jobs:
    Tests-Unitarios-LoginPgats:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '24'
            - name: Notificar início dos testes via discord
              env:
                WEBHOOK: ${{secrets.DISCORD_WEBHOOK_URL}}
              run: |
                curl -H "Content-Type: application/json" \
                -X POST \
                -d "{\"content\": \"Inicio do processo de teste unitários\"}" \
                $WEBHOOK
            - name: Instalando dependência
              run: npm install
            - name: Executando tests e2e
              run: npm run test
            - name: Publicando relatórios
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: Relatorio-test
                path: mochawesome-report
            - name: Notificar sucesso no discord
              if: success()
              uses: sarisia/actions-status-discord@v1
              with:
                webhook: ${{secrets.DISCORD_WEBHOOK_URL}}
                status: success
                title: 'Pipeline conclída com sucesso'
                description: 'Todos os testes passaram'
                color: 0x28A745
            - name: Notificar falha no discord
              if: failure()
              uses: sarisia/actions-status-discord@v1
              with:
                webhook: ${{secrets.DISCORD_WEBHOOK_URL}}
                status: failure
                title: 'Pipeline falhou'
                description: 'Um ou mais testes falharam'
                color: 0xDC3545
